-- Criação da tabela "gastos_animal"
create table gastos_animal (
    id bigint generated by default as identity,
    categoria varchar(255),
    icone varchar(255),
    saldo_inicial numeric(38,2) check (saldo_inicial >= 0),
    primary key (id)
);

-- Criação da tabela "usuario"
create table usuario (
    id bigint generated by default as identity,
    email varchar(255),
    nome varchar(255),
    senha varchar(255),
    primary key (id)
);

-- Criação da tabela "animal" com uma chave estrangeira para "gastos_animal"
create table animal (
    id bigint generated by default as identity,
    dt_nascimento date,
    genero varchar(255),
    idade integer not null,
    nome varchar(255),
    peso float(53) not null,
    raca varchar(255),
    gastos_animal_id bigint,
    primary key (id),
    foreign key (gastos_animal_id) references gastos_animal(id)
);
create table animal (id bigint generated by default as identity, dt_nascimento date, genero varchar(255), idade integer not null, nome varchar(255), peso float(53) not null, raca varchar(255), gastos_animal_id bigint, primary key (id));
create table gastos_animal (id bigint generated by default as identity, categoria varchar(255), icone varchar(255), saldo_inicial numeric(38,2) check (saldo_inicial>=0), primary key (id));
create table usuario (id bigint generated by default as identity, email varchar(255), nome varchar(255), senha varchar(255), primary key (id));
alter table if exists animal add constraint FKohrajg2gavb1pic48bdknginq foreign key (gastos_animal_id) references gastos_animal;
